"""Скрипт для запуска теста в CI и сохраняет в github в actions
В терминале используем команды Git. Сначала git add . 
 - git commit -m " " 
 - git push
 - смотрим в github"""


name: Test

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependecies
        run:
          pip install -r requirements.txt
      - name: Install dependecies
            run:
              pytest --alluredir=allure-results